%% ============================================================================
%  SOC EKF Simulink 模型搭建脚本
%  功能：创建 FC-EMS SOC 估计 Simulink 模型
%  包含：电池模型 + EKF SOC 估计器 + AEKF 扩展
%  运行本脚本生成 Simulink 模型
% ============================================================================
clear; clc; close all;

MODEL_NAME = 'SOC_EKF_Estimator';

%% ============================================================================
%  创建新模型
%% ============================================================================
new_system(MODEL_NAME);
open_system(MODEL_NAME);
set_param(MODEL_NAME, 'Solver', 'FixedStepDiscrete', 'FixedStep', '1');

%% ============================================================================
%  添加模块
%% ============================================================================

% ---- 输入信号 ----
% 负载功率 (Repeating Sequence 模拟工况)
add_block('simulink/Sources/Repeating Sequence', [MODEL_NAME '/P_load']);
set_param([MODEL_NAME '/P_load'], 'TimeValues', '[0 600 1200 1800]', ...
    'OutValues', '[30 50 20 35]');

% FC 功率 (Constant)
add_block('simulink/Sources/Constant', [MODEL_NAME '/P_fc']);
set_param([MODEL_NAME '/P_fc'], 'Value', '35');

% 随机噪声 (Band-Limited White Noise)
add_block('simulink/Sources/Band-Limited White Noise', [MODEL_NAME '/CurrentNoise']);
set_param([MODEL_NAME '/CurrentNoise'], 'Cov', '0.25');

add_block('simulink/Sources/Band-Limited White Noise', [MODEL_NAME '/VoltageNoise']);
set_param([MODEL_NAME '/VoltageNoise'], 'Cov', '0.01');

% ---- 电池模型 ----
% 功率求和
add_block('simulink/Math Operations/Add', [MODEL_NAME '/P_bat']);
set_param([MODEL_NAME '/P_bat'], 'Inputs', '+-');

% MATLAB Function: 电池 SOC 模型
add_block('simulink/User-Defined Functions/MATLAB Function', [MODEL_NAME '/BatteryModel']);
battery_code = [
    'function [SOC, V_t, I_bat] = BatteryModel(P_bat, SOC_init, dt)\n', ...
    '    persistent SOC_curr\n', ...
    '    if isempty(SOC_curr)\n', ...
    '        SOC_curr = SOC_init;\n', ...
    '    end\n', ...
    '    \n', ...
    '    %% OCV 查表参数\n', ...
    '    SOC_BP = [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]'';\n', ...
    '    OCV_LU = [300, 310, 320, 325, 330, 335, 340, 345, 350, 355, 360]'';\n', ...
    '    R_INT = 0.5;\n', ...
    '    Q_BAT = 100;  %% Ah\n', ...
    '    \n', ...
    '    %% 由功率反算电流\n', ...
    '    V_oc = interp1(SOC_BP, OCV_LU, SOC_curr);\n', ...
    '    P_w = P_bat * 1000;  %% kW -> W\n', ...
    '    delta = V_oc^2 - 4 * R_INT * P_w;\n', ...
    '    if delta > 0\n', ...
    '        I_bat = (V_oc - sqrt(delta)) / (2 * R_INT);\n', ...
    '        I_bat = min(max(I_bat, -300), 300);\n', ...
    '    else\n', ...
    '        I_bat = 0;\n', ...
    '    end\n', ...
    '    \n', ...
    '    %% 安时积分\n', ...
    '    SOC_curr = SOC_curr - I_bat / (Q_BAT * 3600) * dt;\n', ...
    '    SOC_curr = min(max(SOC_curr, 0.2), 0.9);\n', ...
    '    \n', ...
    '    %% 端电压\n', ...
    '    V_oc2 = interp1(SOC_BP, OCV_LU, SOC_curr);\n', ...
    '    V_t = V_oc2 - R_INT * I_bat;\n', ...
    '    SOC = SOC_curr;\n', ...
    'end'
];
set_param([MODEL_NAME '/BatteryModel'], 'Script', sprintf(battery_code));

% ---- EKF SOC 估计器 (MATLAB Function) ----
add_block('simulink/User-Defined Functions/MATLAB Function', [MODEL_NAME '/EKF_SOC_Estimator']);
ekf_code = [
    'function SOC_est = EKF_SOC_Estimator(I_meas, V_t_meas, dt)\n', ...
    '    %% EKF SOC 估计器\n', ...
    '    %% 输入: I_meas - 测量电流 (A)\n', ...
    '    %%       V_t_meas - 测量端电压 (V)\n', ...
    '    %%       dt - 采样时间 (s)\n', ...
    '    %% 输出: SOC_est - EKF 估计 SOC\n', ...
    '    \n', ...
    '    %% 持久变量（保持状态在步间传递）\n', ...
    '    persistent x P Q R SOC_init_done\n', ...
    '    \n', ...
    '    %% 电池参数\n', ...
    '    SOC_BP = [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]'';\n', ...
    '    OCV_LU = [300, 310, 320, 325, 330, 335, 340, 345, 350, 355, 360]'';\n', ...
    '    Q_BAT = 100;  %% Ah\n', ...
    '    \n', ...
    '    %% EKF 参数\n', ...
    '    Q_EKF = 5e-5;    %% 过程噪声\n', ...
    '    R_EKF = 0.03;    %% 测量噪声\n', ...
    '    \n', ...
    '    %% 初始化\n', ...
    '    if isempty(SOC_init_done)\n', ...
    '        x = 0.6;  %% 初始 SOC 估计\n', ...
    '        P = 0.1;  %% 初始协方差\n', ...
    '        Q = Q_EKF;\n', ...
    '        R = R_EKF;\n', ...
    '        SOC_init_done = 1;\n', ...
    '    end\n', ...
    '    \n', ...
    '    %% ====== Predict (时间更新) ======\n', ...
    '    x_pred = x - I_meas / (Q_BAT * 3600) * dt;\n', ...
    '    P_pred = P + Q;\n', ...
    '    \n', ...
    '    %% ====== Update (测量更新) ======\n', ...
    '    %% OCV 查表 + 斜率\n', ...
    '    V_pred = interp1(SOC_BP, OCV_LU, x_pred);\n', ...
    '    delta_soc = 1e-4;\n', ...
    '    x_lo = max(x_pred - delta_soc, 0);\n', ...
    '    x_hi = min(x_pred + delta_soc, 1);\n', ...
    '    V_lo = interp1(SOC_BP, OCV_LU, x_lo);\n', ...
    '    V_hi = interp1(SOC_BP, OCV_LU, x_hi);\n', ...
    '    H = (V_hi - V_lo) / (x_hi - x_lo);  %% dOCV/dSOC\n', ...
    '    \n', ...
    '    %% 新息\n', ...
    '    y = V_t_meas - V_pred;\n', ...
    '    \n', ...
    '    %% 卡尔曼增益\n', ...
    '    S = H^2 * P_pred + R;\n', ...
    '    K = P_pred * H / S;\n', ...
    '    \n', ...
    '    %% 状态修正\n', ...
    '    x = x_pred + K * y;\n', ...
    '    x = min(max(x, 0.2), 0.9);\n', ...
    '    \n', ...
    '    %% 协方差更新\n', ...
    '    P = (1 - K * H) * P_pred;\n', ...
    '    P = max(P, 1e-10);\n', ...
    '    \n', ...
    '    SOC_est = x;\n', ...
    'end'
];
set_param([MODEL_NAME '/EKF_SOC_Estimator'], 'Script', sprintf(ekf_code));

% ---- AEKF 扩展 (MATLAB Function) ----
add_block('simulink/User-Defined Functions/MATLAB Function', [MODEL_NAME '/AEKF_Extension']);
aekf_code = [
    'function [SOC_est, R_adapt, Q_adapt, L_adapt] = AEKF_Extension(I_meas, V_t_meas, dt)\n', ...
    '    %% AEKF: 自适应窗口 + 噪声协方差在线调整\n', ...
    '    %% 相比标准 EKF, 增加了:\n', ...
    '    %%   1. Levene 检验检测新息分布变化\n', ...
    '    %%   2. 自适应窗口长度 L\n', ...
    '    %%   3. 基于新息方差的 R/Q 在线更新\n', ...
    '    \n', ...
    '    persistent x P Q R L innov_buf\n', ...
    '    persistent SOC_BP OCV_LU Q_BAT\n', ...
    '    persistent L_min L_max is_init\n', ...
    '    \n', ...
    '    %% 参数初始化\n', ...
    '    if isempty(is_init)\n', ...
    '        x = 0.6; P = 0.1; Q = 5e-5; R = 0.03;\n', ...
    '        L = 50; L_min = 10; L_max = 200;\n', ...
    '        innov_buf = [];\n', ...
    '        SOC_BP = (0:0.1:1)'';\n', ...
    '        OCV_LU = [300;310;320;325;330;335;340;345;350;355;360];\n', ...
    '        Q_BAT = 100;\n', ...
    '        is_init = 1;\n', ...
    '    end\n', ...
    '    \n', ...
    '    %% Predict\n', ...
    '    x_pred = x - I_meas / (Q_BAT * 3600) * dt;\n', ...
    '    P_pred = P + Q;\n', ...
    '    \n', ...
    '    %% Update\n', ...
    '    V_pred = interp1(SOC_BP, OCV_LU, x_pred);\n', ...
    '    d = 1e-4;\n', ...
    '    H = (interp1(SOC_BP, OCV_LU, min(x_pred+d,1)) - ...\n', ...
    '         interp1(SOC_BP, OCV_LU, max(x_pred-d,0))) / (2*d);\n', ...
    '    y = V_t_meas - V_pred;\n', ...
    '    S = H^2 * P_pred + R;\n', ...
    '    K = P_pred * H / S;\n', ...
    '    x = min(max(x_pred + K*y, 0.2), 0.9);\n', ...
    '    P = max((1 - K*H) * P_pred, 1e-10);\n', ...
    '    \n', ...
    '    %% ---- 自适应部分 ----\n', ...
    '    innov_buf = [innov_buf; y];\n', ...
    '    if length(innov_buf) > L_max\n', ...
    '        innov_buf = innov_buf(end-L_max+1:end);\n', ...
    '    end\n', ...
    '    \n', ...
    '    %% 每 10 步执行窗口自适应\n', ...
    '    if mod(length(innov_buf), 10) == 0 && length(innov_buf) >= 20\n', ...
    '        split = floor(length(innov_buf) / 2);\n', ...
    '        y1 = innov_buf(1:split);\n', ...
    '        y2 = innov_buf(split+1:end);\n', ...
    '        \n', ...
    '        %% Levene 检验\n', ...
    '        z1 = abs(y1 - median(y1));\n', ...
    '        z2 = abs(y2 - median(y2));\n', ...
    '        z = [z1; z2];\n', ...
    '        n1 = length(y1); n2 = length(y2);\n', ...
    '        mz1 = mean(z1); mz2 = mean(z2); mz = mean(z);\n', ...
    '        W = (n1+n2-2) * (n1*(mz1-mz)^2 + n2*(mz2-mz)^2) / ...\n', ...
    '            (sum((z1-mz1).^2) + sum((z2-mz2).^2) + 1e-10);\n', ...
    '        \n', ...
    '        %% 窗口调整\n', ...
    '        if W > 3.84  %% chi2(1, 0.05)\n', ...
    '            L = max(round(L * 0.7), L_min);\n', ...
    '        else\n', ...
    '            L = min(round(L * 1.05), L_max);\n', ...
    '        end\n', ...
    '    end\n', ...
    '    \n', ...
    '    %% 噪声协方差自适应\n', ...
    '    L_eff = min(L, length(innov_buf));\n', ...
    '    if L_eff >= 5\n', ...
    '        innov_var = var(innov_buf(end-L_eff+1:end));\n', ...
    '        R = max(innov_var - H^2 * P_pred, 0.001);\n', ...
    '        Q = max(K^2 * innov_var, 1e-8);\n', ...
    '    end\n', ...
    '    \n', ...
    '    SOC_est = x;\n', ...
    '    R_adapt = R;\n', ...
    '    Q_adapt = Q;\n', ...
    '    L_adapt = L;\n', ...
    'end'
];
set_param([MODEL_NAME '/AEKF_Extension'], 'Script', sprintf(aekf_code));

% ---- OCV 查表 (Lookup Table) ----
add_block('simulink/Lookup Tables/Lookup Table', [MODEL_NAME '/OCV_Lookup']);
set_param([MODEL_NAME '/OCV_Lookup'], 'BreakpointsForDimensions1', '[0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0]', ...
    'Table', '[300 310 320 325 330 335 340 345 350 355 360]');

% ---- Display ----
add_block('simulink/Sinks/Scope', [MODEL_NAME '/SOC_Comparison']);
add_block('simulink/Sinks/Scope', [MODEL_NAME '/Error']);
add_block('simulink/Sinks/To Workspace', [MODEL_NAME '/ToWorkspace']);
set_param([MODEL_NAME '/ToWorkspace'], 'VariableName', 'SOC_est_log');

%% ============================================================================
%  连线
%% ============================================================================
% P_load - P_fc = P_bat
add_line(MODEL_NAME, 'P_load/1', 'P_bat/1');
add_line(MODEL_NAME, 'P_fc/1', 'P_bat/2');
add_line(MODEL_NAME, 'P_bat/1', 'BatteryModel/1');

% 电池模型输出
add_line(MODEL_NAME, 'BatteryModel/1', 'SOC_Comparison/1');  % 真实 SOC
add_line(MODEL_NAME, 'BatteryModel/2', 'EKF_SOC_Estimator/2');  % V_t
add_line(MODEL_NAME, 'BatteryModel/3', 'EKF_SOC_Estimator/1');  % I_bat

% EKF 输出
add_line(MODEL_NAME, 'EKF_SOC_Estimator/1', 'SOC_Comparison/2');
add_line(MODEL_NAME, 'EKF_SOC_Estimator/1', 'ToWorkspace/1');

%% ============================================================================
%  模型配置
%% ============================================================================
set_param(MODEL_NAME, 'StopTime', '1800');
save_system(MODEL_NAME);
fprintf('✅ Simulink 模型已创建: %s.slx\n', MODEL_NAME);
fprintf('   打开模型后点击 Run 即可运行 SOC EKF 仿真\n');
