%% Define Bus types
%Bus_FC_Plant
fc_plant_elems(1)=Simulink.BusElement;
fc_plant_elems(1).Name='V_in_act';
fc_plant_elems(1).DataType='double';
fc_plant_elems(2)=Simulink.BusElement;
fc_plant_elems(2).Name='I_in_act';
fc_plant_elems(2).DataType='double';
fc_plant_elems(3)=Simulink.BusElement;
fc_plant_elems(3).Name='V_out_act';
fc_plant_elems(3).DataType='double';
fc_plant_elems(4)=Simulink.BusElement;
fc_plant_elems(4).Name='I_out_act';
fc_plant_elems(4).DataType='double';
fc_plant_elems(5)=Simulink.BusElement;
fc_plant_elems(5).Name='duty_ref';
fc_plant_elems(5).DataType='double';
fc_plant_elems(6)=Simulink.BusElement;
fc_plant_elems(6).Name='eta_act';
fc_plant_elems(6).DataType='double';
fc_plant_elems(7)=Simulink.BusElement;
fc_plant_elems(7).Name='dmdt_H2_act';
fc_plant_elems(7).DataType='double';
fc_plant_elems(8)=Simulink.BusElement;
fc_plant_elems(8).Name='fault';
fc_plant_elems(8).DataType='boolean';
Bus_FC_Plant=Simulink.Bus;
Bus_FC_Plant.Elements=fc_plant_elems;
clear fc_plant_elems
%Bus_Bat_Plant
bat_plant_elems(1)=Simulink.BusElement;
bat_plant_elems(1).Name='V_in_act';
bat_plant_elems(1).DataType='double';
bat_plant_elems(2)=Simulink.BusElement;
bat_plant_elems(2).Name='I_in_act';
bat_plant_elems(2).DataType='double';
bat_plant_elems(3)=Simulink.BusElement;
bat_plant_elems(3).Name='V_out_act';
bat_plant_elems(3).DataType='double';
bat_plant_elems(4)=Simulink.BusElement;
bat_plant_elems(4).Name='I_out_act';
bat_plant_elems(4).DataType='double';
bat_plant_elems(5)=Simulink.BusElement;
bat_plant_elems(5).Name='duty_ref';
bat_plant_elems(5).DataType='double';
bat_plant_elems(6)=Simulink.BusElement;
bat_plant_elems(6).Name='SoC_act';
bat_plant_elems(6).DataType='double';
bat_plant_elems(7)=Simulink.BusElement;
bat_plant_elems(7).Name='R_est';
bat_plant_elems(7).DataType='double';
bat_plant_elems(8)=Simulink.BusElement;
bat_plant_elems(8).Name='fault';
bat_plant_elems(8).DataType='boolean';
Bus_Bat_Plant=Simulink.Bus;
Bus_Bat_Plant.Elements=bat_plant_elems;
clear bat_plant_elems
%Bus_CC
cc_elems(1)=Simulink.BusElement;
cc_elems(1).Name='I_FC_ref';
cc_elems(1).DataType='double';
Bus_CC=Simulink.Bus;
Bus_CC.Elements=cc_elems;
clear cc_elems
%Bus_Logging
log_elems(1)=Simulink.BusElement;
log_elems(1).Name='P_load_est';
log_elems(1).DataType='double';
log_elems(2)=Simulink.BusElement;
log_elems(2).Name='P_load_pred';
log_elems(2).DataType='double';
log_elems(2).Dimensions=N_pred+1;
Bus_Logging=Simulink.Bus;
Bus_Logging.Elements=log_elems;
clear cc_elems